config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to: "pages#home"
  get 'pages/dashboard', to: 'pages#dashboard'
  get 'pages/my_profil', to: 'pages#my_profil'
  get 'pages/user_profil', to: 'pages#user_profil'
  get 'pages/accept_booking', to: 'pages#accept_booking'
  get 'pages/refuse_booking', to: 'pages#refuse_booking'
  get 'pages/results', to: 'pages#results'
  post 'pages/add_profile_picture', to: 'pages#add_profile_picture'
  resources :cruises do
    resources :bookings, only: :create
  end
  resources :user do
    resources :reviews, only: :create
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many_attached :photos
  OPTIONS = ["Accepted", "Refused", "Waiting for approval"]

  belongs_to :cruise
  belongs_to :customer, class_name: "User"
  validates :status, presence: true
  validates_inclusion_of :status, :in => OPTIONS
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  def index
    @bookings = policy_scope(Booking)
  end

  def show
    authorize @booking
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def edit
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.customer_id = current_user[:id]
    @cruise = Cruise.find(params[:cruise_id])
    @booking.cruise_id = @cruise[:id]
    @booking.status = "Waiting for approval"
    authorize @booking

    @booking.save
    redirect_to pages_dashboard_path
  end

  def update
    authorize @booking

    @booking.update(booking_params)

    redirect_to pages_dashboard_path
  end

  def destroy
    authorize @booking
    @booking.destroy

    redirect_to pages_dashboard_path
  end

  # def accept_booking(booking)
  #   booking.status = "Accepted"
  # end

  # def refuse_booking(booking)
  #   booking.status = "Refused"
  # end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:user_description, :number_of_passengers)
  end
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id(booking) %>">

  <p>
    <strong>Cruise:</strong>
    <%= Cruise.find(booking.cruise_id).title %>
  </p>

  <p>
    <strong>Skipper:</strong>
    <%= User.find(Cruise.find(booking.cruise_id).owner_id).first_name %>
  </p>

  <p>
    <strong>Cruise description:</strong>
    <%= Cruise.find(booking.cruise_id).description%>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= Cruise.find(booking.cruise_id).capacity%>
  </p>

<%= link_to "Edit this cruise", edit_cruise_path(Cruise.find(booking.cruise_id).id) %>
<%= link_to "Back to dashboard", pages_dashboard_path %>
</div>

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render "booking", booking: booking%>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container margin-top-negative">
<%= render @booking %>
</div>