config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to: "pages#home"
  get 'pages/dashboard', to: 'pages#dashboard'
  get 'pages/my_profil', to: 'pages#my_profil'
  get 'pages/user_profil', to: 'pages#user_profil'
  get 'pages/accept_booking', to: 'pages#accept_booking'
  get 'pages/refuse_booking', to: 'pages#refuse_booking'
  get 'pages/results', to: 'pages#results'
  post 'pages/add_profile_picture', to: 'pages#add_profile_picture'
  resources :cruises do
    resources :bookings, only: :create
  end
  resources :user do
    resources :reviews, only: :create
  end
end

app/views/pages/_info_window.html.erb
 <% random_photo = cruises.photos.sample %>

<div >
  <%= link_to cruise_path(cruises),  class: "text-decoration-none" do  %>
    <div  class="mini-cruise-card-image text-decoration-none" style="background-image: url('<%= cl_image_path(random_photo.key) %>')"></div>
  <% end %>
    <p><strong><%= cruises.title %></strong></p>

</div>
 <%# "cruise-card-image" %>

app/views/pages/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo"%>

app/views/pages/dashboard.html.erb
<div class="container margin-top-negative">
  <div class ="container text-center elegant-bottom-lign ">
      <h1>My Dashboard</h1>
  </div>
<!-- your requests -->
  <div class="container mt-4">
    <% if @my_bookings.empty? %>
      <h3>You didn't book any cruises yet </h3>
    <% else %>
    <h3>My requests:</h3>
      <div class="row flex">

            <% @my_bookings.each do |booking| %>
            <div class="col-md-4">
              <div class="cruise-card">
                <% random_photo = Cruise.find(booking.cruise_id).photos.sample %>
                <div class="cruise-card-image" style="background-image: url('<%= cl_image_path(random_photo.key, height: 300, width: 400, crop: :fill) %>')"></div>
                <div class="owner-avatar">
                  <div class="d-flex align-items-center">
                    <% if User.find(Cruise.find(booking.cruise_id).owner_id).image.attached? %>
                      <%= link_to image_tag(User.find(Cruise.find(booking.cruise_id).owner_id).image, class: "avatar-white-border m-2"), pages_user_profil_path(User.find(Cruise.find(booking.cruise_id).owner_id)) %>
                    <% else %>
                        <%= image_tag "https://static.vecteezy.com/ti/gratis-vector/p3/7319933-black-avatar-person-icons-user-profile-icon-vector.jpg", class: "avatar m-2"%>
                    <% end %>
                  </div>
                </div>
                <% if booking.status == "Waiting for approval" %>
                  <div class="booking-status-waiting">
                    <span class="p-2"><%= booking.status %></span>
                  </div>
                <% elsif booking.status == "Accepted" %>
                  <div class="booking-status-accepted">
                    <span class="p-2"><%= booking.status %></span>
                  </div>
                <% elsif booking.status == "Refused" %>
                  <div class="booking-status-refused">
                    <span class="p-2"><%= booking.status %></span>
                  </div>
                <% end %>


                <div class="cruise-card-content">
                  <div class="cruise-card-title text-center">
                    <h4><%= Cruise.find(booking.cruise_id).title %></h4>
                    <%= button_to "I don't want to go anymore", booking, method: :delete, class: "btn btn-secondary"%>
                  </div>
                </div>
              </div>
            </div>
            <% end %>

      </div>
    <% end %>
  </div>

<!-- they want to sail with you-->

  <div class="container mt-4">
    <% if @bookings_requests.empty? %>
      <h3> No booking requests for the moment </h3>
    <% else %>
      <h3>They want to sail with you:</h3>
      <div class="row d-flex">

          <% @bookings_requests.each do |request| %>
          <div class="col-md-4">
              <div class="cruise-card">
                <% random_photo = Cruise.find(request.cruise_id).photos.sample %>
                <div class="cruise-card-image" style="background-image: url('<%= cl_image_path(random_photo.key, height: 300, width: 400, crop: :fill) %>')"></div>
                <% if request.status == "Waiting for approval" %>
                  <div class="booking-status-waiting">
                    <span class="p-2"><%= request.status %></span>
                  </div>
                <% elsif request.status == "Accepted" %>
                  <div class="booking-status-accepted">
                    <span class="p-2"><%= request.status %></span>
                  </div>
                <% elsif request.status == "Refused" %>
                  <div class="booking-status-refused">
                    <span class="p-2"><%= request.status %></span>
                  </div>
                <% end %>
                <div class="cruise-card-content">
                  <div class="cruise-card-title text-center">
                    <h4><%= Cruise.find(request.cruise_id).title %></h4>
                  </div>
                  <div class="d-flex align-items-center">
                    <div class="">
                      <% if User.find(request.customer_id).image.attached? %>
                        <%= link_to image_tag(User.find(request.customer_id).image, class: "avatar-white-border"), pages_user_profil_path(User.find(request.customer_id)) %>
                      <% else %>
                        <%= image_tag "https://static.vecteezy.com/ti/gratis-vector/p3/7319933-black-avatar-person-icons-user-profile-icon-vector.jpg", class: "avatar m-2"%>
                      <% end %>
                    </div>
                    <div class="text-center aligne-items-center">
                      <span class="font-italic">"<%= request.user_description %>" </span>
                    </div>
                  </div>
                  <div class="ms-2">
                    <% if User.find(request.customer_id).rate.present? %>
                      <span> <%= User.find(request.customer_id).rate.round(2) %> <i class="fa-sharp fa-solid fa-star " style="color:orange"></i></span>
                    <% end %>
                  </div>
                  <div class="d-flex justify-content-between mt-2">
                  <%= link_to "Accept", pages_accept_booking_path(request), class: 'btn btn-primary'  %>
                  <%= link_to "Refuse", pages_refuse_booking_path(request), class: 'btn btn-danger' %>
                  </div>
                </div>
              </div>
          </div>
          <% end %>

      </div>
    <% end %>
  </div>

</div>

app/views/pages/home.html.erb
<div class="container">

    <div class ="container text-center elegant-bottom-lign ">
      <h1>Get ready for your next adventure</h1>
      <%# <h3>Search your dream cruise</h3> %>
    </div>

    <div class="container search-home">
          <%= form_with url: pages_results_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                id: "form-homepage",
                placeholder: "The adventure starts now"
            %>
          <%= submit_tag "Find your paradise", name: "", class: "btn btn-primary" %>
        <% end %>
    </div>

    <div class="container">
      <div class="map-container">
        <div style="width: 100%; height: 600px;"
        data-controller="map-homepage"
        data-map-homepage-markers-value="<%= @markers.to_json%>"
        data-map-homepage-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

      </div>
    </div>

</div>

app/views/pages/my_profil.html.erb
<div class="container margin-top-negative">
  <div class="mt-5 mb-5">
    <h1><%=@profile.first_name %>'s profile</h1>
  </div>

   <div class="row align-items-center">
    <div class="container margin-top-negative">
      <div class="row">
        <div class="col-8">
          <div class="cruise-show-card">
            <ul class="list-unstyled">
              <li><strong>Email:</strong> <%= @profile.email %></li>
              <li><strong>First Name:</strong> <%= @profile.first_name %></li>
              <li><strong>Last Name: </strong><%= @profile.last_name %></li>
              <li><strong>Gender: </strong><%= @profile.gender %></li>
              <li><strong>Date of birth:</strong> <%= @profile.date_of_birth %></li>
              <li><strong>Address:</strong> <%= @profile.address %></li>
              <li><strong>Postcode: </strong><%= @profile.postcode %></li>
              <li><strong>City:</strong> <%= @profile.city %></li>
              <li><strong>Sailing experience:</strong> <%= @profile.sailing_experience %></li>
              <li><strong>Biography: </strong><%= @profile.description %></li>
            </ul>
          </div>
        </div>
        <div class="col-4 d-flex  align-items-center justify-content-center">
        <% if current_user.image.attached? %>
          <%= image_tag(current_user.image, class: "profile-image") %>
        <% else %>
          <p>No profile picture</p>
        <% end %>
        </div>
      </div>

      <div>

      </div>
    </div>

  </div>

  <div class="container margin-top-negative">
 <!--   <h1>Reviews as a passenger</h1>
    Attente de la table review -->
  </div>

  <div class="container margin-top-negative">
   <!--   <h1>Reviews as a skipper</h1>
     Attente de la table review -->
  </div>

  <div class="text-center mt-3">
    <%= link_to "Edit your profile", edit_user_registration_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/pages/results.html.erb
<div class="container mt-3">
  <% if @cruises.empty? %>
    <div class="row">
      <div class="col-12 mx-auto text-center ">
        <div class="title-results elegant-bottom-lign">
          <h1>Oupsi no results "<%= params[:query].upcase%>"</h1>
        </div>
        <div class="mt-5 mb-5">
          <img src="https://cdn-icons-png.flaticon.com/512/6134/6134065.png" alt="no results" width="200"/>
        </div>
        <%= link_to "Back to home", root_path, class: "btn btn-primary mt-4" %>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col-12 mx-auto text-center elegant-bottom-lign">
        <div class="title-results">
          <h1>We found <%= @cruises.length %> cruises around "<%= params[:query].upcase%>"</h1>
        </div>
      </div>
    </div>
    <div class="row d-flex mt-5">
      <div class="col-4">
        <% @cruises.each do |cruise| %>
          <div>
            <div class="cruise-card">
              <% random_photo = cruise.photos.sample %>
              <div class="cruise-card-image" style="background-image: url('<%= cl_image_path(random_photo.key, height: 300, width: 400, crop: :fill) %>')"></div>
              <div class="owner-avatar">
                <div class="d-flex align-items-center">
                    <% if User.find(cruise.owner_id).image.attached? %>
                      <% if user_signed_in? %>
                        <% if cruise.owner_id == current_user.id%>
                          <%= link_to image_tag(User.find(cruise.owner_id).image, class: "avatar-white-border m-2"), pages_my_profil_path %>
                        <% else %>
                          <%= link_to image_tag(User.find(cruise.owner_id).image, class: "avatar-white-border m-2"), pages_user_profil_path(User.find(cruise.owner_id)) %>
                        <% end %>
                      <% else %>
                           <%= image_tag(User.find(cruise.owner_id).image, class: "avatar-large me-3") %>
                      <% end %>
                    <% else %>
                      <%= image_tag "https://static.vecteezy.com/ti/gratis-vector/p3/7319933-black-avatar-person-icons-user-profile-icon-vector.jpg", class: "avatar m-2"%>
                  <% end %>
                </div>
              </div>
              <div class="cruise-card-content">
                <div class="cruise-card-title text-center">
                  <h4><%= cruise.title %></h4>
                </div>
                <div class="text-center">
                <p><%= cruise.itinerary %></p>
                </div>
                <div class="flex justify-content-center">
                  <div class="flex align-items-center">
                    <i class="fa-solid fa-sailboat me-1"></i>
                    <span> <%= cruise.boat_model %></span>
                  </div>
                  <div class="flex align-items-center ms-3">
                    <i class="fa-solid fa-euro-sign me-1"></i>
                    <span> <%= cruise.price %></span>
                  </div>
                  <div class="flex align-items-center ms-3">
                    <i class="fa-sharp fa-solid fa-person me-1"></i>
                    <span> <%= cruise.capacity %></span>
                  </div>
                </div>
              </div>
              <div class="cruise-card-actions text-center">
                <div class="">
                  <%= link_to "More info", cruise_path(cruise), class: "btn btn-primary btn-sm text-center" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-8 text-center sticky-top">
        <div style="width: 100%; height: 600px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json%>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/user_profil.html.erb
<div class="container margin-top-negative">
  <div class="mt-5 mb-5">
    <h1><%=@profile.first_name %>'s profile</h1>
    <% if @profile.rate.nan? %>
      <p>No rates yet for <%= @profile.first_name %></p>
    <% else %>

      <% @profile.target_users.each do |review| %>
      <% @profile.rate += review.rating %>
      <% end %>
      <% @profile.rate = @profile.rate / @profile.target_users.length  %>
      <h2> <%= @profile.rate.round(2) %> <i class="fa-sharp fa-solid fa-star " style="color:orange"></i></h2>
      <% @profile.save %>
    <% end %>


  </div>
   <div class="row align-items-center">
    <div class="container margin-top-negative">
      <div class="row d-flex">
        <div class="col-8">
          <div class="cruise-show-card">
            <ul class="list-unstyled">
              <li><strong>Email:</strong> <%= @profile.email %></li>
              <li><strong>First Name:</strong> <%= @profile.first_name %></li>
              <li><strong>Last Name:</strong> <%= @profile.last_name %></li>
              <li><strong>Gender:</strong> <%= @profile.gender %></li>
              <li><strong>Date of birth:</strong> <%= @profile.date_of_birth %></li>
              <li><strong>Address:</strong> <%= @profile.address %></li>
              <li><strong>Postcode:</strong> <%= @profile.postcode %></li>
              <li><strong>City:</strong> <%= @profile.city %></li>
              <li><strong>Sailing experience:</strong> <%= @profile.sailing_experience %></li>
              <li><strong>Biography: </strong> <%= @profile.description %></li>
            </ul>
          </div>
        </div>
        <div class="col-4 d-flex  align-items-center justify-content-center">
        <% if current_user.image.attached? %>
          <%= image_tag(@profile.image, class: "profile-image") %>
        <% else %>
           <%= image_tag "https://static.vecteezy.com/ti/gratis-vector/p3/7319933-black-avatar-person-icons-user-profile-icon-vector.jpg", class: "profile-image"%>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="container">

  <div class="cruise-show-card">
    <%= simple_form_for([@profile, @review]) do |f| %>
      <%= f.input :content %>
      <%= f.input :rating, collection: 0..5%>
      <%= f.button :submit, "Give #{@profile.first_name } a review", class:"btn btn-primary"%>
    <% end %>
  </div>


    <% if @profile.target_users.blank? %>
      <div class="cruise-show-card">
        Be the first to leave a review for <%= @profile.first_name %>
      </div>
    <% else %>
      <% @profile.target_users.each do |review| %>
        <div class="cruise-show-card">
        <div class="d-flex align-items-center">
          <% if User.find(review.creator_user_id).image.attached? %>
              <%= image_tag(User.find(review.creator_user_id).image, class: "avatar m-2") %>
          <% else %>
              <%= image_tag "https://static.vecteezy.com/ti/gratis-vector/p3/7319933-black-avatar-person-icons-user-profile-icon-vector.jpg", class: "avatar m-2"%>
          <% end %>
           <span> <%= User.find(review.creator_user_id).first_name%> gave <%= review.rating %>     <i class="fa-sharp fa-solid fa-star " style="color:orange"></i></span>
        </div>
        <div class="m-2">
          <p>"<%= review.content %>"</p>
        </div>
        </div>
      <% end %>
    <% end %>

</div>